name: movie_catalog
description: "A 10 practice RKMP app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_cache_manager: ^3.4.1
  google_fonts: ^6.3.2
  logger: ^2.6.2
  get_it: ^9.0.5
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^17.0.0


  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  file_picker: ^10.3.6
  epub_view: ^3.2.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  enough_convert: ^1.0.0
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

  flutter_lints: ^6.0.0
  flutter_launcher_icons: 0.11.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

#  my_package:
#    git:
#      url: https://github.com/username/my_package.git
#      ref: main
#      path: lib
#
#
#  local_package:
#     path: ../example/local_package

